version: "2"

services:
  phoenix:
    build: .
    image: phoenix
    container_name: phoenix
#    command: sh -c "while true; do sleep 1; done"
    command: mix phoenix.server
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    links:
      - db:db
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    restart: always

volumes:
  db-data:
    driver: local
